//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_DottiesShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonNhap()
        {
            this.CT_HoaDonNhap = new HashSet<CT_HoaDonNhap>();
        }
    
        public int MaHDN { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDonNhap> CT_HoaDonNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
