//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_DottiesShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CT_HoaDonBan = new HashSet<CT_HoaDonBan>();
            this.CT_HoaDonNhap = new HashSet<CT_HoaDonNhap>();
        }
    
        public int MaSP { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenSP { get; set; }
        public string MauSac { get; set; }
        public double DonGia { get; set; }
        public double GiaSale { get; set; }
        public string GhiChu { get; set; }
        public int SoLuong { get; set; }
        public string KichThuoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDonBan> CT_HoaDonBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDonNhap> CT_HoaDonNhap { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
