//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_DottiesShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public string GhiChu { get; set; }
    }
}
